src/WebApplication/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApplication.Extensions;
using WebApplication.Models;
using WebApplication.Services;

namespace WebApplication.Controllers
{
    [Authorize]
    public class RentalsController : Controller
    {
        private readonly IGatewayService _gatewayService;

        public RentalsController(IGatewayService gatewayService)
        {
            _gatewayService = gatewayService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var rentals = await _gatewayService.Get<IList<RentalViewModel>>("rentals/me");

            return rentals.IsSuccess ?
                View(rentals.Content) : 
                View().WithWarning("Oops!", rentals.ErrorMessage);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id,
            ReservationSearchModel searchModel)
        {
            var rental = await _gatewayService.Get<RentalViewModel>($"rentals/{id}");

            var reservations = await _gatewayService
                .Get<IList<ReservationViewModel>>($"/rentals/{id}/reservations");

            // filtering should be done on backend, not here. oh no... anyway
            IEnumerable<ReservationViewModel> filteredReservations = reservations.Content;
            if (!string.IsNullOrEmpty(searchModel.FromDate) &&
                DateTime.TryParse(searchModel.FromDate, out var fromDate))
            {
                filteredReservations =
                    reservations.Content.Where(res => res.StartDateUtc >= fromDate);
            }
            if (!string.IsNullOrEmpty(searchModel.ToDate) &&
                DateTime.TryParse(searchModel.ToDate, out var toDate))
            {
                filteredReservations =
                    reservations.Content.Where(res => res.EndDateUtc <= toDate);
            }
            
            var viewModel = new RentalDetailsViewModel
            {
                Details = rental.Content,
                Reservations = filteredReservations?.ToList() ?? new List<ReservationViewModel>()
            };
            viewModel.ReservationSearchModel.FromDate = searchModel.FromDate;
            viewModel.ReservationSearchModel.ToDate = searchModel.ToDate;

            return rental.IsSuccess
                ? View(viewModel)
                : RedirectToAction(nameof(Index))
                    .WithWarning("Oops!", rental.ErrorMessage);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new RentalViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(RentalViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            
            var rental = await _gatewayService.Post("rentals", model);

            return rental.IsSuccess ?
                RedirectToAction(nameof(Index)).WithSuccess("Puiku!", "Sukurtas naujas nuomos objektas.") : 
                View().WithWarning("Oops!", rental.ErrorMessage);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var rental = await _gatewayService.Get<RentalViewModel>($"rentals/{id}");
            
            return rental.IsSuccess ?
                View(rental.Content) :
                View().WithWarning("Oops!", rental.ErrorMessage);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RentalViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Edit), new {id = model.Id});
            }
            
            var rental = await _gatewayService.Put("rentals", model);

            return rental.IsSuccess ?
                RedirectToAction(nameof(Edit), new { id = model.Id }).WithSuccess("Yay!", "Sėkmingai atnaujinote nuomos objektą.") :
                RedirectToAction(nameof(Edit), new { id = model.Id }).WithWarning("Oops!", rental.ErrorMessage);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, string confirmationInput)
        {
            var rental = await _gatewayService.Get<RentalViewModel>($"rentals/{id}");

            if (!rental.IsSuccess)
            {
                return RedirectToAction(nameof(Edit), new { id }).WithWarning("Oops!", rental.ErrorMessage);
            }
            
            if (confirmationInput != rental.Content.Name)
            {
                return RedirectToAction(nameof(Edit), new { id }).WithWarning("Oops!", 
                    "Neteisingai įvesta patvirtinimo žinutė.");
            }

            var response = await _gatewayService.Delete($"rentals/{id}");

            return response.IsSuccess ?
                RedirectToAction(nameof(Index)).WithSuccess("Yay!", $"Nuomos objektas {rental.Content.Name} ištrintas.") :
                RedirectToAction(nameof(Edit), new { id }).WithWarning("Ooops:/", rental.ErrorMessage);
        }
    }
}

src/WebApplication/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Hosting
@using Microsoft.Extensions.Hosting
@inject IWebHostEnvironment WebHostEnvironment;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Nuomos valdymo sistema</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Nuomos valdymo sistema</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Pradinis</a>
                        </li>
                        @if (WebHostEnvironment.IsDevelopment())
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Secure">Secure</a>
                            </li>
                        }

                        @if (User?.Identity?.IsAuthenticated == true)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Rentals" asp-action="Index">Mano nuoma</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Atsijungti</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Prisijungti</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Register">Registruotis</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/WebApplication/Views/Shared/_Notifications.cshtml
@{
    var type = (string)TempData["_status.type"];
    var title = (string)TempData["_status.title"];
    var body = (string)TempData["_status.body"];
}

@if (!string.IsNullOrEmpty(type))
{
    <div class="alert alert-@type alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>@title</strong> @body
    </div>
}